manual_seed: 100
checkpoint_dir: # gs://...
logs_dir: # gs://...

dataset:
  root_dir: ./data
  save_dir: ./data/dataset
  data_dirs:
    Fuji: [2160, 3240]
    SICEvL: [2160, 3840]
    SICEvM: [1080, 1920]
    SICEvS: [720, 1280]
    SMID: [2160, 3240]
    LOL: [400, 600]
    LOLv1: [384, 384]
    RELLISUR: [625, 625]
    SDSD: [1080, 1920]
    Sony: [2160, 3240]
  validation_split: 0.2
  batch_size:
    train: 8
    val: 8
  use_augment: true
  use_shuffle: true

model:
  out_channels: 3
  n_feat: 40
  stage: 1
  num_blocks: [1, 2, 2]

training:
  total_iter: 300000
  loss: mae
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true
  scheduler:
    periods: [92000, 208000]
    m_mul: 1
    lr_mins: [0.0003, 0.000001]
  optimizer:
    lr: 0.0002
    clipnorm: true
    betas: [0.9, 0.999]
